language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    
    sudo: false
    # Before build starts
    before_script:
    - chmod +x grailsw

    script: ./grailsw refresh-dependencies
    && ./grailsw "test-app -integration"
 
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
